### ISSUE TITLE
Getting Exception while getting access token 

### ISSUE THREAD

**Issue by ArslanAfzalBhatti** [MediaFire/mediafire-csharp-open-sdk#3]
"One or more parameters for this request are invalid"
The Stack Trace is :
   'at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ResumableUpload.Sample.Main(String[] args) in c:\Users\Arslan Afzal\Documents\Visual Studio 2015\Projects\ConsoleApplication4\ConsoleApplication4\Program.cs:line 42
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()'

and the error occurred at 'Main().Wait();
in "ResumableUpload"  can you please help me why i am getting this error ?

**Comment by DVDPT** [comment]
Hi,
Did you fill the configuration fields?
` private const string AppId = "";
        private const string AppKey = "";

        private const string Email = "";
        private const string Password = "";
`

**Comment by ArslanAfzalBhatti** [comment]
yes

**Comment by ArslanAfzalBhatti** [comment]
i had filled it up and also checked the Email and Password

**Comment by DVDPT** [comment]
How about the file, did you provide a correct full path?

**Comment by ArslanAfzalBhatti** [comment]
yes i have provided the correct path of file and the file size is less then 1 MB , Actually the error occurred during authentication when the email address showed then suddenly Main().Wait() produce the error that "One or more parameters for this request are invalid" !

**Comment by DVDPT** [comment]
Hi, just tested it out, and the GetSessionToken method works fine, did you change any other configuration option on the sample?

**Comment by ArslanAfzalBhatti** [comment]
no i just provide app key and Id and my email address as well as password

**Comment by ArslanAfzalBhatti** [comment]
i am just using the ResumableUpload sample just in my application

**Comment by ArslanAfzalBhatti** [comment]
let me know how can i share my application with you so that the actual error can be debug ? please

**Comment by DVDPT** [comment]
Hi, the error says it all, something that you are adding is not right. If you like you can share you sample.cs with me ;)

**Comment by ArslanAfzalBhatti** [comment]
[Sample.txt](https://github.com/MediaFire/mediafire-csharp-open-sdk/files/236401/Sample.txt)
 
Please check it

**Comment by DVDPT** [comment]
Swap the appid with the appkey ;)

**Comment by ArslanAfzalBhatti** [comment]
at which line ? 
i swapped it but same error occurred :(

**Comment by DVDPT** [comment]
Your appid is with the appkey values ;). Just swap their values and you are done :+1:

**Comment by ArslanAfzalBhatti** [comment]
lolz this is really embracing :+1:

**Comment by ArslanAfzalBhatti** [comment]
and the code works fine thank you so much dear :)

**Comment by DVDPT** [comment]
No problem ;)

**Comment by ArslanAfzalBhatti** [comment]
Dear Diogo i am using this code in my application when i call this code for
upload purpose then it goes unresponsive. the file of code is attached in
mail named MFHandler please take a look once on it and i the code from here
i call the code is also attached in an other file named as Caller please
take a look why it does so ? Your help is needed i would really appreciate
your effort.

On Tue, Apr 26, 2016 at 4:11 PM, Diogo Cardoso <notifications@github.com>
wrote:

> Closed #3
> <https://github.com/MediaFire/mediafire-csharp-open-sdk/issues/3>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaFire/mediafire-csharp-open-sdk/issues/3#event-641322025>
>

   public ActionResult MF(long? Id)
        {
            var dblistVid = db.Videos.FirstOrDefault(v => v.Id == Id);
            new MediaFireHandler(dblistVid.Path).StartUpload();
            return View();
        }
﻿using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using MediaFireSDK;
using MediaFireSDK.Model;
using Final.Models;

namespace MfHandler
{
    public class MediaFireHandler
    {
        private string filePath;

        public string FilePath
        {
            get { return filePath; }
            set { filePath = value; }
        }
        public MediaFireHandler(string path)
        {
            filePath = path;
        }
            
        private const string AppId = "51830";
        private const string AppKey = "f4je25ijpk6sjuw22ncj18utfe19zamyxf6oxpem";

        private const string Email = "arslanafzalbhatti@gmail.com";
        private const string Password = "Whats*745";
        //
        //  The file to be uploaded
        //
       // private static string FilePath = MyVide.Path; //@"F:\Dancing.MP4";

        public void StartUpload()
        {
            ServicePointManager.Expect100Continue = false;
            var config = new MediaFireApiConfiguration
               (
                   appId: AppId,
                   apiKey: AppKey,
                   apiVersion: "1.5",
                   automaticallyRenewToken: true,
                   chunkTransferBufferSize: 1024
               );

            _agent = new MediaFireAgent(config);
            SMain().Wait();
        }


        private static IMediaFireAgent _agent;

        async Task SMain()
        {
          //  Console.WriteLine("Signing in {0}...", Email);
           await _agent.User.GetSessionToken(Email,Password);

            var fileInfo = GetFile();

            var resumableController = new MfResumableFileUploadController(_agent, fileInfo.Length, fileInfo.OpenRead(), fileInfo.Name);
            resumableController.CalculateFileHash();


            var checkDetails = await _agent.Upload.Check(fileInfo.Name, resumableController.FileLength, hash: resumableController.FileHash, resumable: true);

            if (checkDetails.FileExists)
            {
//                Console.WriteLine("File already exists in the server, please choose another one");
                return;
            }

  //          Console.WriteLine("Unit Size:\t{0}", checkDetails.ResumableUpload.UnitSize);
    //        Console.WriteLine("Nr Of Units:\t{0}", checkDetails.ResumableUpload.NumberOfUnits);



            await resumableController.Upload(checkDetails.ResumableUpload);

        }


        private FileInfo GetFile()
        {
            var finfo = new FileInfo(FilePath);

      //      Console.WriteLine("File: {0}\t\n", finfo.Name);
        //    Console.WriteLine("\t\t(bytes)");

          //  Console.WriteLine("TotalSize:\t{0}\n", finfo.Length);

            return finfo;
        }

    }
}

**Comment by ArslanAfzalBhatti** [comment]
another thing is that it is does't through any kind of exception its just keep loading

**Comment by DVDPT** [comment]
You are locking the context of the request and creating a deadlock situation XD. (more info on: http://enterprisecraftsmanship.com/2014/12/20/pitfalls-of-async-await/)
The following should work:

> Task.Run(()=>new MediaFireHandler(dblistVid.Path).StartUpload();).Wait();

**Comment by ArslanAfzalBhatti** [comment]
thanks once again and sorry for inconvenience :)
